name: "Jo-el's Words!"
favicon: null
layout_spectrum: 0.9944
typography_spectrum: 0.46865
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.9842235636897385
  lightness: 0.9396840068511665
  saturation: 0.08373535517603159
  rhythmicContrast: 0.16849897452630103
purpose: []
